Website = "https://github.com/craig-warner/solve-spelling-bee-fyne"

[Details]
  Icon = "assets.solve-sb.png"
  Name = "Solve Spelling Bee"
  ID = "com.warnerbits.solvespellingbee"
  Version = "1.0.0"
  Build = 9
